name: oggm_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - shapely
  - matplotlib
  - Pillow
  - netcdf4
  - scikit-image
  - scikit-learn
  - configobj
  - xarray
  - pytest
  - dask
  - bottleneck
  - gdal=3.3
  - pyproj
  - cartopy
  - geopandas
  - rasterio
  - rioxarray
  - pytables
  - salem
  - motionless
  - ipython
  - numpydoc
  - seaborn
  - pip
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/pytest-mpl
    - git+https://github.com/OGGM/massbalance-sandbox
    - oggm==1.6.0
    - certifi